In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice1=a[2:6]
print(slice1)

[3 4 5 6]


In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice2=a[::2]
print(slice2)

[1 3 5 7 9]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice3=a[::3]
print(slice3)

[1 4 7]


In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice4=a[::4]
print(slice4)

[1 5 9]


In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
rev_array=a[::-1]
print(rev_array)

[9 8 7 6 5 4 3 2 1]


In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=a[0:2,1:3]
print(subarr)

[[2 3]
 [5 6]]


In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=a[:1,:3]
print(subarr)

[[1 2 3]]


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
col1=a[:,0]
print(col1)
row1=a[0,:]
print(row1)

[1 4 7]
[1 2 3]


In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:3:2])

[[1 2 3]
 [7 8 9]]


In [16]:
import numpy as np
import array
a=array.array('i',[1,2,3,4,5])
print(a[0])
print(a[3])

1
4


In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,0])
print(a[2,1])

1
8


In [21]:
import numpy as np
arr=[10,20,30]
print(arr[1])
print(arr[-1])
print(arr[1:4])

20
30
[20, 30]


In [24]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[arr>25])
print(arr[[1,3]])

[30 40 50]
[20 40]


In [3]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
res=np.array_split(arr,3)
print(res)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
