In [5]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)


(array([1, 4]),)


In [9]:
arr=np.array([1,6,2,7,6,4])
x=np.where(arr%2==0)
print(x)

(array([1, 2, 4, 5]),)


In [39]:
arr=np.array([0,1,2,2,3,8,9])
x=np.searchsorted(arr,8,side='left')
print(x)

5


In [41]:
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))

[[4 7 9]
 [1 4 9]]


In [43]:
arr=np.array([31,78,91,100])
x=[False,True,False,True]
newarr=arr[x]
print(x)
print(newarr)

[False, True, False, True]
[ 78 100]


In [45]:
filter=arr>70
newarr=arr[filter]
print(filter)
print(newarr)

[False  True  True  True]
[ 78  91 100]
